### ISSUE TITLE
font size changes on headers

### ISSUE THREAD

**Issue by jots** [rgieseke/ta-markdown#3]
great module!

alt-1 - alt-6 changes the font size of the selected line which is awesome, but I'd like to tweak the sizes themselves but I don't see how or where you're doing that.    I'd love the ability to change fonts for parts of a buffer for other reasons as well so would love it if you could point me to how it is done.

**Comment by rgieseke** [comment]
It's not done in this module but in the Scintillua lexer that ships with Textadept:

https://github.com/rgieseke/scintillua/blob/master/lexers/markdown.lua#L84
(Link to my mirror)

You can either copy the `markdown.lua` file to your `~/.textadept/lexers/` and change the sizes there or try extending the existing like:

https://foicica.com/lists/code/201612/3465.html

Same would apply to other lexers where you might want to change font sizes.
